import type { Metadata } from "next";
import "./globals.css";
import ScrollHandler from "./_components/effects/scroll-handler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark mx-auto max-w-130">
      <body>
        <ScrollHandler />
        {children}
      </body>
    </html>
  );
}
