import type { Metadata } from "next";
import "./globals.css";
import ScrollHandler from "./effects/scroll-handler";
import { Toaster } from "./_components/ui/sonner";
import Footer from "./_components/footer";
import AuthProvider from "./_providers/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark mx-auto max-w-130">
      <body>
        <AuthProvider>
          <ScrollHandler />
          <div className="flex h-full flex-col">
            <div className="flex-1">{children}</div>
            <Toaster />
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
